name: Build, Push, and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend .
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and Deploy Frontend
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/todo-frontend
          docker stop todo-frontend || true
          docker rm todo-frontend || true
          docker run -d -p 80:80 --name todo-frontend --env-file /path/to/frontend.env ${{ secrets.DOCKER_USERNAME }}/todo-frontend

